services:
  prowlarr:
    image: linuxserver/prowlarr:latest 
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+1
    networks: 
      mediarr:
        aliases:
          - prowlarr
    volumes:
      - ./configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on: 
      - flaresolverr

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+1
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    networks: 
      mediarr:
        aliases:
          - qbittorrent
    volumes: 
      - ./configs/qbittorrent:/config 
      - downloadsDir:/mnt/downloads 
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyseerr: 
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    hostname: jellyseerr 
    networks: 
      mediarr:
        aliases:
          - jellyseerr
    user: 1000:1000 
    environment: 
      - TZ=Etc/GMT+1
      - JELLYFIN_TYPE=emby
    ports: 
      - 5055:5055 
    volumes: 
      - ./configs/jellyseerr:/app/config 
    restart: unless-stopped 
    depends_on: 
      - sonarr 
      - radarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+1
    networks: 
      mediarr:
        aliases:
          - radarr
    volumes:
      - ./configs/radarr:/config
      - downloadsDir:/mnt/downloads
      - mediaDir:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+1
    volumes:
      - ./configs/sonarr:/config
      - downloadsDir:/mnt/downloads
      - mediaDir:/mnt/media
    networks: 
      mediarr:
        aliases:
          - sonarr
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr: 
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr 
    hostname: flaresolverr 
    networks: 
      mediarr:
        aliases:
          - flaresolverr
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none} 
      - TZ=Etc/GMT+1

  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    networks: 
      mediarr:
        aliases:
          - emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+1
    volumes:
      - ./configs/emby:/config
      - mediaDir:/mnt/media
    ports:
      - 8096:8096
    restart: unless-stopped

networks: 
  mediarr: 
    driver: bridge

volumes:
  mediaDir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/media
  downloadsDir:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/karu/Downloads
